player addAction["Take Fuel Can", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Fuel_can"],  5] select 0); [true,"fuelF",1] call fnc_handleinv; hint "You have taken a fuel can."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Fuel_can"],  5] select 0) < 4 and (waste_carryW + (["fuelF"] call fnc_itemweight)) <= waste_maxCarry and ((nearestObjects[getpos player, ["Fuel_can"], 3] select 0) getVariable "fuel")'];
player addAction["Take Empty Fuel Can", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Fuel_can"],  5] select 0); [true,"fuelE",1] call fnc_handleinv; hint "You have taken a empty fuel can."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Fuel_can"],  5] select 0) < 4 and (waste_carryW + (["fuelE"] call fnc_itemweight)) <= waste_maxCarry and !((nearestObjects[getpos player, ["Fuel_can"], 3] select 0) getVariable "fuel")'];
player addAction["Take Toolkit", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Suitcase"],  5] select 0); [true,"repair",1] call fnc_handleinv; hint "You have taken a repair kit."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Suitcase"],  5] select 0) < 4 and (waste_carryW + (["repair"] call fnc_itemweight)) <= waste_maxCarry'];
player addAction["Take Medkit", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["CZ_VestPouch_EP1"],  5] select 0); [true,"medkit",1] call fnc_handleinv; hint "You have taken a medkit."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["CZ_VestPouch_EP1"],  5] select 0) < 4 and (waste_carryW + (["medkit"] call fnc_itemweight)) <= waste_maxCarry '];
//player addAction["Take Canned food", "noscript.sqf", '(nearestobjects [getpos player, ["Land_stand_small_EP1"],  5] select 0) setVariable["food",((nearestobjects [getpos player, ["Land_stand_small_EP1"],  5] select 0) getVariable "food")-1,true]; player setVariable["canfood",(player getVariable "canfood")+1,true]; hint "You have taken some canned food"; player playmove "AinvPknlMstpSlayWrflDnon";',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_stand_small_EP1"],  5] select 0) < 5 and (player getVariable "canfood") < 3 and (nearestobjects [getpos player, ["Land_stand_small_EP1"],  5] select 0) getVariable "food" > 0'];
player addAction["Take Canned food", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Bag_EP1"],  5] select 0); [true,"canfood",1] call fnc_handleinv; hint "You have taken some canned food."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Bag_EP1"],  5] select 0) < 5 and (waste_carryW + (["canfood"] call fnc_itemweight)) <= waste_maxCarry '];
player addAction["Bottle up water", "noscript.sqf", '(nearestobjects [getpos player, ["Land_Barrel_water"],  5] select 0) setVariable["water",((nearestobjects [getpos player, ["Land_Barrel_water"],  5] select 0) getVariable "water")-1,true]; [true,"water",1] call fnc_handleinv; hint "You have taken some water."; player playmove "AinvPknlMstpSlayWrflDnon";',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Barrel_water"],  5] select 0) < 5 and (waste_carryW + (["water"] call fnc_itemweight)) <= waste_maxCarry and (nearestobjects [getpos player, ["Land_Barrel_water"],  5] select 0) getVariable "water" > 0'];
player addAction["Take bottle of water", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Teapot_EP1"],  5] select 0); [true,"water",1] call fnc_handleinv; hint "You have taken a bottle of water."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Teapot_EP1"],  5] select 0) < 5 and (waste_carryW + (["water"] call fnc_itemweight)) <= waste_maxCarry '];
player addAction["Pickup Money", "noscript.sqf", ' waste_money = ((nearestobjects [getpos player, ["EvMoney"],  5] select 0) getVariable "money")+waste_money; deleteVehicle (nearestobjects [getpos player, ["EvMoney"],  5] select 0);player playmove "AinvPknlMstpSlayWrflDnon"; hint format["You have picked up $%1",(nearestobjects [getpos player, ["EvMoney"],  5] select 0) getVariable "money"];',1,false,false,"",'player distance (nearestobjects [getpos player, ["EvMoney"],  5] select 0) < 5'];
player addAction["Fill Water Bottle", "noscript.sqf", '[true,"water",1] call fnc_handleinv; hint "You have filled a water bottle";',1,false,false,"",' player distance (nearestobjects [getpos player, ["Land_pumpa"],  3] select 0) < 3 and (waste_carryW + (["water"] call fnc_itemweight)) <= waste_maxCarry'];
player addAction["Cook meat", "core\misc\cook.sqf", '', 1,false,false,"",'waste_rabit > 0 OR waste_cow > 0 OR waste_chicken > 0 OR waste_goat > 0 OR waste_boar > 0 AND inflamed (nearestObjects[getPos player, ["Land_Campfire_burning"],5] select 0);'];

//Refuel at gas stations
player addAction["Refuel Jerry can", "noscript.sqf", '[false,"fuelE",1] call fnc_handleinv; [true,"fuelF",1] call fnc_handleinv; hint "You have refueled a empty jerry can";',0,false,false,"",'player distance (nearestObjects[getPos player, ["Land_A_FuelStation_Feed"], 3] select 0) < 3 AND (waste_fuelE) > 0 AND ((waste_carryW + (["fuelF"] call fnc_itemweight)) - (["fuelE"] call fnc_itemweight)) <= waste_maxCarry'];

//Gut animal actions?
player addAction["Gut Boar", "core\func\fnc_gutanimal.sqf","boar",1,false,false,"",'not ALIVE (nearestObjects[getPos player, ["WildBoar"],  1] select 0) && !((nearestObjects[getPos player, ["WildBoar"],  1] select 0) getVariable "gut")'];
player addAction["Gut Chicken", "core\func\fnc_gutanimal.sqf","chicken",1,false,false,"",'not ALIVE (nearestObjects[getPos player, ["Cock","Hen"],  1] select 0) && !((nearestObjects[getPos player, ["cock","hen"],  1] select 0) getVariable "gut")'];
player addAction["Gut Cow", "core\func\fnc_gutanimal.sqf","cow",1,false,false,"",'NOT ALIVE (nearestObjects[getPos player, ["Cow01","Cow02","Cow03","Cow04"],  1] select 0) && !((nearestObjects[getPos player, ["Cow01","Cow02","Cow03","Cow04"],  1] select 0) getVariable "gut")'];
player addAction["Gut Goat", "core\func\fnc_gutanimal.sqf","goat",1,false,false,"",'not ALIVE (nearestObjects[getPos player, ["goat"],  1] select 0) && !((nearestObjects[getPos player, ["goat"],  1] select 0) getVariable "gut")'];
player addAction["Gut Rabbit", "core\func\fnc_gutanimal.sqf","rabbit",1,false,false,"",'NOT ALIVE (nearestObjects[getPos player, ["Rabbit"],  1] select 0) && !(isNil {(nearestObjects[getPos player, ["Rabbit"],  1] select 0) getVariable "gut"})'];
//Take meat from animal
player addAction["Take raw meat", "core\func\fnc_takemeat.sqf",nearestObjects[getPos player, ["WildBoar"], 1] select 0,0,false,false,"",' !isNil {(nearestObjects[getpos player, ["WildBoar","cock","hen","Rabbit","Cow01","Cow02","Cow03","Cow04","goat"], 5] select 0) getVariable "gut"} && (nearestObjects[getpos player, ["WildBoar","cock","hen","Rabbit","Cow01","Cow02","Cow03","Cow04","goat"], 5] select 0) getVariable "meat" > 0'];

//Raw Meat Pickup Actions
player addAction["Take Raw Goat Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); [true,"goat",1] call fnc_handleinv; hint "You have taken raw goat meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and (waste_carryW + (["goat"] call fnc_itemweight)) <= waste_maxCarry and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "goat" AND ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Raw Cow Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); [true,"cow",1] call fnc_handleiv; hint "You have taken raw cow meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and (waste_carryW + (["cow"] call fnc_itemweight)) <= waste_maxCarry and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "cow" AND ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Raw Chicken Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); [true,"chicken",1] call fnc_handleinv; hint "You have taken raw chicken meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and (waste_carryW + (["chicken"] call fnc_itemweight)) <= waste_maxCarry and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "chicken" AND ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Raw Boar Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); [true,"boar",1] call fnc_handleinv; hint "You have taken raw boar meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and (waste_carryW + (["boar"] call fnc_itemweight)) <= waste_maxCarry and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "boar" AND ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Raw Rabbit Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); [true,"rabbit",1] call fnc_handleinv; hint "You have taken raw rabbit meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and (waste_carryW + (["rabbit"] call fnc_itemweight)) <= waste_maxCarry and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "rabit" AND ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];

//Cooked Meat Pickup Actions
player addAction["Take Cooked Goat Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); [true,"goatc",1] call fnc_handleinv; hint "You have taken Cooked goat meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and (waste_carryW + (["goat"] call fnc_itemweight)) <= waste_maxCarry and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "goat" AND !((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Cooked Cow Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); [true,"cowc",1] call fnc_handleinv; hint "You have taken Cooked cow meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and (waste_carryW + (["cow"] call fnc_itemweight)) <= waste_maxCarry and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "cow" AND !((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Cooked Chicken Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); [true,"chickenc",1] call fnc_handleinv; + 1; hint "You have taken Cooked chicken meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and (waste_carryW + (["chicken"] call fnc_itemweight)) <= waste_maxCarry and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "chicken" AND !((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Cooked Boar Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); [true,"boarc",1] call fnc_handleinv; hint "You have taken Cooked boar meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and (waste_carryW + (["boar"] call fnc_itemweight)) <= waste_maxCarry and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "boar" AND !((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Cooked Rabbit Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); [true,"rabbitc",1] call fnc_handleinv; hint "You have taken Cooked rabbit meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and (waste_carryW + (["rabbit"] call fnc_itemweight)) <= waste_maxCarry && ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "rabit" AND !((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];

//Money crate SM
player addAction["Take Cash", "noscript.sqf", 'waste_money = waste_money + ((nearestobjects [getpos player, ["Misc_cargo_cont_tiny"],  5] select 0) getVariable "money"); player playmove "AinvPknlMstpSlayWrflDnon"; hint format["You have picked up $%1",(nearestobjects [getpos player, ["Misc_cargo_cont_tiny"],  5] select 0) getVariable "money"]; sleep 2; deleteVehicle (nearestobjects [getpos player, ["Misc_cargo_cont_tiny"],  5] select 0);',0,false,false,"",'player distance (nearestobjects [getpos player, ["Misc_cargo_cont_tiny"],  3] select 0) < 2 AND ((nearestObjects[player, ["Misc_cargo_cont_tiny"], 3] select 0) getVariable "isMoney")'];

//Arm the bomb
player addAction ["Take Bomb", "noscript.sqf", 
'[true,"bomb",1] call fnc_handleinv; deleteVehicle (nearestobjects [getpos player, ["bomb"],  2] select 0); hint "You have picked up a time bomb"; player playmove "AinvPknlMstpSlayWrflDnon"'
,0,false,false,"",
' player distance (nearestobjects [getpos player, ["bomb"],  2] select 0) < 3 AND !((nearestobjects [getpos player, ["bomb"],  2] select 0) getVariable "bArmed") AND !waste_hasBomb AND (waste_carryW + (["bomb"] call fnc_itemweight)) <= waste_maxCarry'
];

//Pickup Spawn Beacon
player addAction["Take Spawn Beacon", "noscript.sqf",
'if([true,"beacon",1] call fnc_handleinv) then { deleteVehicle (nearestObjects [getPos player, ["Satelit"], 2] select 0); titleText["You have picked up a spawn beacon.","PLAIN"]; titleFadeOut 3; player playmove "AinvPknlMstpSlayWrflDnon" };',
0,false,false,"",
'player distance (nearestObjects [getPos player, ["Satelit"], 3] select 0) < 3 AND !((nearestObjects [getPos player, ["Satelit"], 3] select 0) getVariable "beacon") AND !waste_hasBeacon AND (waste_carryW + (["beacon"] call fnc_itemweight)) <= waste_maxCarry'];

player addAction["Re-equip Spawn Beacon", "noscript.sqf",
'if([true,"beacon",1] call fnc_handleinv) then { player switchMove "AinvPknlMstpSlayWrflDnon_medic"; AnimSync = [player,"AinvPknlMstpSlayWrflDnon_medic"]; publicVariable "AnimSync"; waitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; waste_sBeacon = ObjNull; waste_sBuse = 0; deleteMarkerLocal "myBeacon"; deleteVehicle (nearestObjects [getPos player, ["Satelit"], 2] select 0); titleText["You re-equiped your spawn beacon.","PLAIN"]; titleFadeOut 3; };',
0,false,false,"",
'!isNull waste_sBeacon AND (alive waste_sBeacon) AND (player distance (getPos waste_sBeacon) < 3 ) AND (waste_carryW + (["beacon"] call fnc_itemweight)) <= waste_maxCarry'];

//Restrain them
//player addAction["Restrain player", "noscript.sqf",' [nil,(nearestObjects[player, ["Man","Man"], 3] select 1), rSwitchMove, "civillying01"] call RE;',0,false,false,"",' animationState (nearestObjects[player, ["Man","Man"], 3] select 1) == "adthpercmstpslowwrfldnon_4"'];
