waste_fnc_pMenu = compile preprocessFile "player_system\init.sqf"; //Wasteland Player Menu
onRespawn = compile preprocessfile "core\onRespawn.sqf"; //Precompile OnRespawn actions
onKilled = compile preprocessfile "core\onKilled.sqf"; //Precompile OnKilled actions
onFired = compile preprocessfile "core\onFired.sqf"; //Precompile OnFired actions
waste_fnc_hit = compile preprocessfile "core\misc\hit.sqf"; //PreCompile rifle butt/punch
waste_fnc_dropFood = compile preprocessfile "core\misc\inv_fnc.sqf"; //Precompile inv Dropfood
SHK_pos = compile preprocessfile "core\misc\SHK_pos.sqf"; //Precompile SHK Position
waste_beacon_set = compile PreProcessFile "core\misc\fnc_beacon.sqf"; //Set beacon fnc
fnc_cheat_report = compile preprocessFile "core\misc\cheat_monitor.sqf"; //Compile Cheat report..
waste_init_vars = compile preprocessFile "core\client_vars.sqf"; //Compile Client Vars... No idea why i'm doing this though...
waste_pActions = compile preprocessFile "core\playerActions.sqf"; //whatever 
fnc_hTime = compile preprocessFile "core\misc\fnc_hTime.sqf"; //Can't remember it's use but has meaning.
keysDown = compile preprocessFile "core\misc\keyHandler.sqf";
waste_ai_roam = compile PreProcessFile "core\ai_roam.sqf";
waste_ai_fnc = compile preProcessFile "core\ai_fnc.sqf";
fnc_index = compile preprocessFile "core\misc\fnc_index.sqf";
fnc_handleDamage = compile preprocessFile "core\misc\fnc_handleDamage.sqf";
fnc_hud = compile preprocessFile "core\misc\fnc_hud.sqf";
fnc_handleinv = compile preprocessFile "core\func\fnc_inv.sqf";
fnc_itemweight = compile preprocessFile "core\func\fnc_itemweight.sqf";
fnc_getvar = compile preprocessFile "core\func\fnc_getvar.sqf";
fnc_updateMenu = compile preProcessfile "player_system\updatemenu.sqf";
fnc_refuel = compile preProcessFile "core\misc\refuel.sqf";;
fnc_repair = compile preProcessFile "core\misc\repair.sqf";